[project]
name = "fp8-auto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.2",
    "rich>=13.9.4",
    "ruff>=0.9.3",
    "torch>=2.5.1",
]
